spring.application.name=LifeOS

spring.datasource.url=jdbc:postgresql://localhost:5432/lifeos
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

minio.url=localhost
minio.secure=false
minio.port=9000
minio.user=Frey
minio.password=123456789
minio.bucket=user-profile-pic

